#! /bin/bash

set -e

if [ $EUID -ne 0 ]; then
    echo "$(basename $0) must be run as root"
    exit 1
fi

microcode_flag=""
if grep -q "microcode" "/etc/mkinitcpio.conf"; then
    microcode_flag="# "
fi

function initramfs_subvol() {
    local subvol=$1
    if [ -z "$subvol" ]; then
        echo "No subvol found" >&2
        exit 1
    fi

    cd $subvol
    # Mount necessary file systems
    mount -t proc /proc proc/
    mount -t sysfs /sys sys/
    mount --rbind /dev dev/
    mount --rbind /etc/mkinitcpio.d etc/mkinitcpio.d/

    # Set R/W permissions
    btrfs property set -fts ${SUBVOL} ro false

    chroot ${SUBVOL} /bin/bash <<EOF
# Commands to be ran in chroot

### Create distro mkinitcpio preset
echo '
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="/boot/vmlinuz-linux"
${microcode_flag}ALL_microcode=(/boot/*-ucode.img)

PRESETS="default"

default_image="/boot/initramfs-linux.img"
' > /etc/mkinitcpio.d/\${NAME%%-*}.preset

### Rebuild Initramfs with custom preset
mkinitcpio -p \${NAME%%-*}
EOF
    # Set back to R/O permissions
    btrfs property set -fts ${SUBVOL} ro true
    # unmount filesystems
    umount -l ${SUBVOL}/proc
    umount -l ${SUBVOL}/sys
    mount --make-rslave ${SUBVOL}/dev
    umount -l ${SUBVOL}/dev
    umount -l ${SUBVOL}/etc/mkinitcpio.d

}

function initramfs_boot() {
    local path=$1
    if [ -z "$ID" ]; then
        echo "No ID found" >&2
        exit 1
    fi
    if [ -z "$BUILD" ]; then
        echo "No BUILD found" >&2
        exit 1
    fi
    if [ -z path ]; then
        echo "No path found" >&2
        exit 1
    fi

    cat > "/etc/mkinitcpio.d/${ID}.preset" <<EOF
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="$path/$BUILD/vmlinuz-linux"
${microcode_flag}ALL_microcode=($path/$BUILD/*-ucode.img)

PRESETS="default"

default_image="$path/initramfs-linux.img"
EOF
    # If we are not doing a deployment then this will be used for local installs to rebuild initramfs
    mkinitcpio -p $ID
}

# Check if script is being ran frmo the install media
if [ -d /tmp/frzr_root ]; then

    if [ -d "${SUBVOL}" ]; then

        initramfs_subvol "${SUBVOL}"
    else
        echo "No deployment directory found"
        exit 1
    fi
else
    echo "We don't appear to be running from an arch install media"
fi

# Build initramfs from within a deployed system
if [ -d /frzr_root ]; then

    if [ -n "$SUBVOL" ]; then
        ### Grabbing name of the new deployed system
        ID=$(grep '^ID=' "$SUBVOL/etc/os-release" | awk -F= '{ print $2 }' | sed 's/"//g')
        VERSIONID=$(grep '^VERSION_ID=' "$SUBVOL/etc/os-release" | awk -F= '{ print $2 }' | sed 's/"//g')
        BUILDID=$(grep '^BUILD_ID=' "$SUBVOL/etc/os-release" | awk -F= '{ print $2 }' | sed 's/"//g')
    else
        ### Grabbing name of the currently deployed system
        ID=$(grep '^ID=' /etc/os-release | awk -F= '{ print $2 }' | sed 's/"//g')
        VERSIONID=$(grep '^VERSION_ID=' /etc/os-release | awk -F= '{ print $2 }' | sed 's/"//g')
        BUILDID=$(grep '^BUILD_ID=' /etc/os-release | awk -F= '{ print $2 }' | sed 's/"//g')
    fi

    # 如果 BUILDID 包含_ 则只取最后一个_之后的部分
    if [[ $BUILDID == *"_"* ]]; then
        BUILDID=$(echo $BUILDID | awk -F_ '{print $NF}')
    fi

    BUILD="$ID"-"$VERSIONID"_"$BUILDID"
    DEPLOYMENT_PATH="/frzr_root/deployments/$BUILD"

    if [[ ! -d $DEPLOYMENT_PATH ]]; then
        echo "No deployment found for $BUILD"
        exit 1
    fi

    # Get locked state
    RELOCK=0
    LOCK_STATE=$(btrfs property get -fts "$DEPLOYMENT_PATH")
    if [[ $LOCK_STATE == *"ro=true"* ]]; then
        btrfs property set -fts ${DEPLOYMENT_PATH} ro false
        RELOCK=1
    else
        echo "Filesystem appears to be unlocked"
    fi

    echo "Generating configuration for $BUILD"

    ### Rebuild Initramfs with custom preset

    if [ -n "$SUBVOL" ]; then
        initramfs_subvol "${SUBVOL}"
    elif [[ -d "/efi/${BUILD}" ]] && grep -q "HOOKS=.*systemd" /etc/mkinitcpio.conf; then
        initramfs_boot "/efi"
    else
        initramfs_boot "/frzr_root/boot"
    fi

    if [[ $RELOCK == 1 ]]; then
        btrfs property set -fts ${DEPLOYMENT_PATH} ro true
    else
        # Move rebuilt images to the unlocked location if system was unlocked prior
        if [[ -d /boot/$BUILD ]]; then
            cp /boot/$BUILD/* /boot
        fi

        if [[ -d /efi/$BUILD ]]; then
            cp /efi/$BUILD/* /efi
            cp /efi/$BUILD/* /boot
        fi

        if [[ -d /frzr_root/boot/$BUILD ]]; then
            cp /frzr_root/boot/$BUILD/* /frzr_root/boot
            cp /frzr_root/boot/$BUILD/* /boot
        fi
    fi
fi
